export const ADD_COUNTER_VALUE = "ADD_COUNTER_VALUE";
export const SUB_COUNTER_VALUE = "SUB_COUNTER_VALUE";
export const STORE_VALUE = "STORE_VALUE";
export const DELETE_STORED_VALUE = "DELETE_VALUE";
